### ISSUE TITLE
version issues

### ISSUE THREAD

**Issue by ungoldman** [toddself/nanorequest#7]
Hi @toddself 👋 

Doing some maintenance and I noticed that there are a few issues with upgrading nanorequest from a consumer perspective:

- latest version in master is v3.0.0
- latest tag in releases is v2.0.3
- latest version on npm is v4.0.1

In short: I have no idea what's going on! I'm unable to find a v4.0.0 let alone v4.0.1 in the source, so I'm quite wary of updating at all. Might you have some memory of what the version status for this fair repo is good sir?

Hope all's well otherwise, cheers from stumptown

**Comment by toddself** [comment]
hello!

Version 3 is lost to the aaaaaages mostly because it was broken and nothing was depending on it. And the machine that the tag was generated on is in the hands of a former employer :)

Version 4 just got pushed (along with 4.0.1 and 4.0.2) -- the differences between version 2 and 4 is that version 3 it got converted into typescript.  Version 4 fixes the bad export that version 3 had.

This adds no new features (unless you want a typescript definition), and if it helps, the tests between version 2 and 4 are nearly identical (the only thing that changes is the port the server runs on):

https://github.com/toddself/nanorequest/compare/63a4dac...toddself:master#diff-909a41ddc788a202bd78a335d77d3361 

Everything should sync up now :)


Hope all is well!

**Comment by ungoldman** [comment]
Thanks for the speedy response and the updated commits! All my questions are answered.

This comparison might help future adventurers:

https://github.com/toddself/nanorequest/compare/v2.0.3...v4.0.2

**Comment by ungoldman** [comment]
Noting for future generations migrating from 2.x to 4.x:

`nanorequest` is now exported as a named function, there is no longer a default export

for those using commonJS:

```js
// 2.x
const nanorequest = require('nanorequest')

// 4.x
const { nanorequest } = require('nanorequest')
```
